### PR TITLE
Added OSX Support for Hide

### PR DESCRIPTION
**Pull request by onehundredfeet**
Added a few details and a conditional define for OSX support.  

It also contains a few fixes that may work for Linux users as well.

### CODE REVIEW

**Comment by ncannasse** [comment]
I think these should be not done using conditional compilation but runtime OS detection.

**Comment by onehundredfeet** [comment]
I will update it

**Comment by onehundredfeet** [comment]
Updated.

**Comment by ncannasse** [comment]
Thanks!

**Pull request merged**
